### ISSUE TITLE
Array/Struct hive type are not yet implemented. Which version supports it? or do you have any implementation for it?

### ISSUE THREAD

**Issue by nikitakadam** [fsprojects/FSharp.Data.HiveProvider#18]

**Comment by dsyme** [comment]
I don't think there's an implementation for this. Would you like to contribute one?

**Comment by moloneymb** [comment]
There are multiple issues at multiple levels that make supporting array / structs very difficult. If you are planning on using complex data types I would recommend Spark. Support for complex data types would outweigh the benefit from the type provider. The 3rd option would be to create a spark type provider but I have not had the time to build one yet.
